name: lightningsword
version: '${project.version}'
main: org.exampl.lightningsword.Lightningsword
api-version: '1.20'
commands:
  lightningsword:
    description: Gives you a Lightning Sword
    usage: /<command>